# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch history
      run: git fetch --unshallow --filter=tree:0 origin $GITHUB_REF

    - name: Fetch tags
      run: git fetch origin +refs/tags/*:refs/tags/*

    - name: Determine version (pull request)
      if: github.event_name == 'pull_request'
      run: echo version="$(git describe --always --tags --match 'v*' ${{github.event.pull_request.head.sha}})-pr-$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

    - name: Determine version (other)
      if: github.event_name != 'pull_request'
      run: echo version="$(git describe --always --tags ${{github.sha}})" >> $GITHUB_ENV

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -Pmod_version="$(echo "${{env.version}}" | cut -c2- | sed -e '0,/-/ s/-/+/')"

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: dist/
        
    - name: Archive mapping.txt
      uses: actions/upload-artifact@v2
      with:
        name: Mappings
        path: build/tmp/proguard/mapping.txt
